export const EXERCISE_DB: Record<string, string[]> = {
  chest: [
    'Bench Press',
    'Incline Bench Press',
    'Decline Bench Press',
    'Dumbbell Fly',
    'Incline Dumbbell Fly',
    'Push-Up',
    'Wide Push-Up',
    'Cable Crossover',
    'Dip',
    'Chest Dip',
    'Pec Deck',
    'Cable Fly',
    'Dumbbell Pullover',
  ],
  back: [
    'Deadlift',
    'Pull-Up',
    'Chin-Up',
    'Barbell Row',
    'Dumbbell Row',
    'Lat Pulldown',
    'Cable Row',
    'T-Bar Row',
    'Pendlay Row',
    'Rack Pull',
    'Straight-Arm Pulldown',
    'Face Pull',
    'Reverse Fly',
    'Hyperextension',
  ],
  shoulders: [
    'Overhead Press',
    'Seated Dumbbell Press',
    'Lateral Raise',
    'Front Raise',
    'Face Pull',
    'Arnold Press',
    'Machine Shoulder Press',
    'Cable Lateral Raise',
    'Upright Row',
    'Shrug',
    'Rear Delt Fly',
  ],
  arms: [
    'Barbell Curl',
    'Dumbbell Curl',
    'Hammer Curl',
    'Preacher Curl',
    'Concentration Curl',
    'Cable Curl',
    'Tricep Pushdown',
    'Skull Crusher',
    'Overhead Tricep Extension',
    'Tricep Kickback',
    'Close-Grip Bench Press',
    'Diamond Push-Up',
    'Reverse Curl',
    'Wrist Curl',
  ],
  legs: [
    'Squat',
    'Front Squat',
    'Romanian Deadlift',
    'Leg Press',
    'Leg Curl',
    'Leg Extension',
    'Calf Raise',
    'Bulgarian Split Squat',
    'Hack Squat',
    'Goblet Squat',
    'Sumo Deadlift',
    'Hip Thrust',
    'Glute Bridge',
    'Walking Lunge',
    'Step-Up',
    'Nordic Curl',
    'Seated Calf Raise',
  ],
  core: [
    'Plank',
    'Side Plank',
    'Crunch',
    'Leg Raise',
    'Hanging Leg Raise',
    'Cable Crunch',
    'Russian Twist',
    'Ab Wheel Rollout',
    'Mountain Climber',
    'V-Up',
    'Hollow Hold',
    'L-Sit',
    'Dragon Flag',
    'Pallof Press',
  ],
  compound: [
    'Power Clean',
    'Clean and Jerk',
    'Snatch',
    'Farmers Walk',
    'Trap Bar Deadlift',
    'Push Press',
    'Hang Power Clean',
    'Power Snatch',
    'Overhead Squat',
    'Zercher Squat',
  ],
  cardio: [
    'Treadmill Run',
    'Row Machine',
    'Assault Bike',
    'Jump Rope',
    'Box Jump',
    'Burpee',
    'Battle Ropes',
    'Stair Climber',
    'Elliptical',
    'Sled Push',
    'Sled Pull',
    'Ski Erg',
  ],
  crossfit: [
    'Thruster',
    'Wall Ball',
    'Kettlebell Swing',
    'Double Under',
    'Muscle Up',
    'Toes to Bar',
    'Bar Muscle Up',
    'Handstand Push-Up',
    'GHD Sit-Up',
    'Rope Climb',
    'Pistol Squat',
    'Ring Dip',
    'Box Jump',
  ],
};

export const ALL_EXERCISES: string[] = Object.values(EXERCISE_DB).flat();

export const BIG4_EXERCISES = ['Bench Press', 'Squat', 'Deadlift', 'Overhead Press'];

export function searchExercises(query: string, limit = 10): string[] {
  if (!query || query.length < 1) {
    return ALL_EXERCISES.slice(0, limit);
  }
  const q = query.toLowerCase();
  return ALL_EXERCISES.filter((e) => e.toLowerCase().includes(q)).slice(0, limit);
}

export function getExercisesByMuscleGroup(group: string): string[] {
  return EXERCISE_DB[group] ?? [];
}
